### ISSUE TITLE
Add support for multiple symbols

### ISSUE THREAD

**Issue by darkf** [MartinThoma/write-math#48]
More than one symbol, e.g. "1 + 2", does not recognize (except as MULTISYMBOL). It would be very useful if it could recognize more than one symbol.

It would also be nice if it recognized e.g. 2<sup>3</sup>, or 2<sub>3</sub>.

**Comment by MartinThoma** [comment]
This is tracked in https://github.com/MartinThoma/hwrt/issues/22 - however, I have to say that I'm currently working on other projects.
